# Generated by Django 5.2.1 on 2025-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_campus_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='campus',
        ),
        migrations.AddField(
            model_name='student',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='seccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
