# Generated by Django 5.2.1 on 2025-05-07 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='members',
            field=models.ManyToManyField(related_name='course_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
