# Generated by Django 5.2.1 on 2025-05-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_privacy_accepted_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_accepted',
        ),
    ]
