# Generated by Django 5.2.1 on 2025-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('type', models.CharField(choices=[('schedule', 'Schedule Change'), ('room', 'Room Change'), ('news', 'News'), ('announcement', 'Announcement')], default='announcement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('target_groups', models.ManyToManyField(related_name='notifications', to='courses.coursegroup')),
            ],
        ),
    ]
