# Generated by Django 5.2.1 on 2025-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_campuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('schedule', 'Cambio de Horario'), ('room', 'Cambio de Sala'), ('suspension', 'Suspensión de Clases'), ('announcement', 'Aviso')], default='announcement', max_length=20),
        ),
    ]
